spring.application.name=f1-spring-cloud-config-server
server.port=8012

spring.cloud.config.server.git.uri=https://github.com/prat-33/my-microservices-app.git
spring.cloud.config.server.git.search-paths=f1-app-config
#Username password not needed for public repo
##spring.cloud.config.server.git.username=${GIT_USERNAME}
#spring.cloud.config.server.git.password=${GIT_PASS}
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main

management.endpoints.web.exposure.include=busrefresh

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.security.user.name=admin
spring.security.user.password=123456789
spring.security.user.roles=ADMIN

spring.security.client.user.name=client
spring.security.client.user.password=123456789
spring.security.client.user.roles=CLIENT